### ISSUE TITLE
E/flutter (27120): 'package:share/share.dart': Failed assertion: line 83 pos 15: 'path != null': is not true.

### ISSUE THREAD

**Issue by agnoam** [d-silveira/flutter-share#3]
Hi @d-silveira  I have another problem.
This plugin working good on share of one thing. But when I share my app with intent of multiple files I got exception on your code, (**my code not running at all**).

This is the log of my application:
````E/flutter (27120): [ERROR:flutter/shell/platform/android/android_context_gl.cc(217)] Could not make the context current
E/flutter (27120): [ERROR:flutter/shell/platform/android/android_context_gl.cc(53)] EGL Error: EGL_BAD_ACCESS (12290)
I/MainActivity(27120): receiving shared files!
I/flutter (27120): Share received - {0: content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fshare_image_1516813324332.png, 1: content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fshare_image_1516813378399.png, type: image/png, is_multiple: true}
E/flutter (27120): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (27120): 'package:share/share.dart': Failed assertion: line 83 pos 15: 'path != null': is not true.
E/flutter (27120): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
E/flutter (27120): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
E/flutter (27120): #2      new Share.file (package:share/share.dart)
E/flutter (27120): #3      Share.fromReceived (package:share/share.dart:141:24)
E/flutter (27120): #4      ReceiveShareState._receiveShareInternal (package:share/receive_share_state.dart:40:24)
E/flutter (27120): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
E/flutter (27120): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
E/flutter (27120): #7      _DelayedData.perform (dart:async/stream_impl.dart:578:14)
E/flutter (27120): #8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694:11)
E/flutter (27120): #9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654:7)
E/flutter (27120): #10     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (27120): #11     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/FlutterActivityDelegate(27120): onResume setting current activity to this
E/BpSurfaceComposerClient(27120): Failed to transact (-1)
E/BpSurfaceComposerClient(27120): Failed to transact (-1)
I/zygote64(27120): Do partial code cache collection, code=60KB, data=47KB
I/zygote64(27120): After code cache collection, code=60KB, data=47KB
I/zygote64(27120): Increasing code cache capacity to 256KB````

**Comment by d-silveira** [comment]
I will investigate it, thanks

**Comment by agnoam** [comment]
Keep me posted...

**Comment by agnoam** [comment]
Are you fixed the problem already ?

**Comment by agnoam** [comment]
Hey how are you ? 
anything new ?

**Comment by d-silveira** [comment]
Hi, I didn't find the issue yet, as soon as I have something I'll let you know, thanks

**Comment by agnoam** [comment]
What's going on with the plugin ?
Any progress ?

**Comment by agnoam** [comment]
Something new ?
